### PR TITLE
Add open rally

### PR DESCRIPTION
**Pull request by ArthurREGNARD**

### CODE REVIEW

**Comment by shamblett** [comment]
Looks good but I'd like some unit tests please, in a similar vein to what we have already, i.e. a simple and complex transformation. We need to see what the transform does, this will help in future with maintenance and bug fixing.

**Comment by ArthurREGNARD** [comment]
I put some test, with input openRally XML exemple.

**Comment by shamblett** [comment]
Ok thanks, I'll have a look at this.

**Review by shamblett — APPROVED** [review]
Ok, ready to merge

**Pull request merged**
