### PR TITLE
Option to use local name for nodes

### PR DESCRIPTION
**Pull request by faithoflifedev**
I came across a situation using xml2json on an complex XML file produced as par of the [Onvif XML spec](https://www.onvif.org/specs/core/ONVIF-Core-Specification.pdf) where only the Badgerfish transformer would work, but due to the factors of the XML the node names sometime caused issue.  By using the localName for nodes, the documents can be processed successfully.

### CODE REVIEW

**Comment by shamblett** [comment]
IT would be good if there was a unit test for this, if you could supply an example of xml and what the resulting json transform looks like I'll write the test.

**Comment by faithoflifedev** [comment]
Here is a sample XML response:
`<soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
	<soapenv:Header/>
	<soapenv:Body>
		<tns:getDataResponse xmlns:tns="https://urchin.com/api/urchin/v1/">
			<record>
			<recordId>1</recordId>
			<dimensions>
				<dimension name="u:month">2008-02-00T00:00:00Z</dimension>
			</dimensions>
			<metrics>
				<u:hits xmlns:u="https://urchin.com/api/urchin/v1/">836</u:hits>
				<u:bytes xmlns:u="https://urchin.com/api/urchin/v1/">1953960</u:bytes>
			</metrics>
			</record>
		</tns:getDataResponse>
	</soapenv:Body>
</soapenv:Envelope>`

Note the use of **xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"**  meaning that "soapenv" has been assigned as the key for the http://www.w3.org/2003/05/soap-envelope namespace.

The problem that the PR solves is that since the **key** is implementation dependent (i.e. one manufacturer will assign "soapenv as the key, while another might assign "ENV"), using the key in the node name makes the resulting json from xml2json dependent on the implementation as well.  

Please let me know if you need me to provide any additional info.

**Comment by faithoflifedev** [comment]
Sorry, I forgot to provide the resulting transform: (with "useLocalNameForNodes: true")

`{"Envelope": {"@xmlns": [{"soapenv": "http://www.w3.org/2003/05/soap-envelope"}], "Header": {}, "Body": {"getDataResponse": {"@xmlns": [{"tns": "https://urchin.com/api/urchin/v1/"}], "record": {"recordId": {"$": "1"}, "dimensions": {"dimension": {"@name": "u:month", "$": "2008-02-00T00:00:00Z"}}, "metrics": {"hits": {"@xmlns": [{"u": "https://urchin.com/api/urchin/v1/"}], "$": "836"}, "bytes": {"@xmlns": [{"u": "https://urchin.com/api/urchin/v1/"}], "$": "1953960"}}}}}}}`

and without: (the default)

`{"soapenv:Envelope": {"@xmlns": [{"soapenv": "http://www.w3.org/2003/05/soap-envelope"}], "soapenv:Header": {}, "soapenv:Body": {"tns:getDataResponse": {"@xmlns": [{"tns": "https://urchin.com/api/urchin/v1/"}], "record": {"recordId": {"$": "1"}, "dimensions": {"dimension": {"@name": "u:month", "$": "2008-02-00T00:00:00Z"}}, "metrics": {"u:hits": {"@xmlns": [{"u": "https://urchin.com/api/urchin/v1/"}], "$": "836"}, "u:bytes": {"@xmlns": [{"u": "https://urchin.com/api/urchin/v1/"}], "$": "1953960"}}}}}}}`

**Comment by faithoflifedev** [comment]
To add to the above.  If the namespace of the original XML sample where changed:

`<ENV:Envelope xmlns:ENV="http://www.w3.org/2003/05/soap-envelope"> <ENV:Header/> <ENV:Body> <tns:getDataResponse xmlns:tns="https://urchin.com/api/urchin/v1/"> <record> <recordId>1</recordId> <dimensions> <dimension name="u:month">2008-02-00T00:00:00Z</dimension> </dimensions> <metrics> <u:hits xmlns:u="https://urchin.com/api/urchin/v1/">836</u:hits> <u:bytes xmlns:u="https://urchin.com/api/urchin/v1/">1953960</u:bytes> </metrics> </record> </tns:getDataResponse> </ENV:Body> </ENV:Envelope>`

Now the key names in the json response have changed.

`{"ENV:Envelope": {"@xmlns": [{"ENV": "http://www.w3.org/2003/05/soap-envelope"}], "ENV:Header": {}, "ENV:Body": {"tns:getDataResponse": {"@xmlns": [{"tns": "https://urchin.com/api/urchin/v1/"}], "record": {"recordId": {"$": "1"}, "dimensions": {"dimension": {"@name": "u:month", "$": "2008-02-00T00:00:00Z"}}, "metrics": {"u:hits": {"@xmlns": [{"u": "https://urchin.com/api/urchin/v1/"}], "$": "836"}, "u:bytes": {"@xmlns": [{"u": "https://urchin.com/api/urchin/v1/"}], "$": "1953960"}}}}}}}`

**Comment by shamblett** [comment]
Thanks for the examples and the explanation, I'll update the unit tests, documentation etc. and re publish the package.

**Comment by shamblett** [comment]
Package updated and re published at version 5.1.0.

**Pull request merged**
